"""empty message

Revision ID: 32f0cb5ac9cb
Revises: 7d881aeb1086
Create Date: 2022-08-21 22:08:09.130357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32f0cb5ac9cb'
down_revision = '7d881aeb1086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('guest_num', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'guest_num')
    # ### end Alembic commands ###
