"""empty message

Revision ID: 97d610ed3ff9
Revises: 32f0cb5ac9cb
Create Date: 2022-08-28 05:11:36.411451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97d610ed3ff9'
down_revision = '32f0cb5ac9cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('category', sa.String(length=20), nullable=False))
    op.add_column('listings', sa.Column('cleaning_fee', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'cleaning_fee')
    op.drop_column('listings', 'category')
    # ### end Alembic commands ###
