"""empty message

Revision ID: 32f0cb5ac9cb
Revises: 7d881aeb1086
Create Date: 2022-08-21 22:08:09.130357

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '32f0cb5ac9cb'
down_revision = '7d881aeb1086'
branch_labels = None
depends_on = None


def upgrade():
    if environment == "production":
        op.execute(f"ALTER TABLE bookings SET SCHEMA {SCHEMA};")
        #  add an ALTER TABLE command here for each table created in the file

    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('guest_num', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'guest_num')
    ### end Alembic commands ###
